language: python
python:
    - 2.7
    - 3.3
    - 3.4
    - 3.5
    - pypy
    - pypy3

matrix:
  include:
    - language: generic
      python: 2.7
      os: osx
    - language: generic
      python: 3.3
      os: osx
    - language: generic
      python: 3.5
      os: osx
    - language: generic
      python: pypy
      os: osx

before_install:
    - pip install --quiet coverage flake8 pyyaml

install:
    - python setup.py install

script:
    - make test
    - coverage run --omit='*/site-packages/*,*/distutils/*' ./test/test.py
    - coverage report --show-missing

after_success:
    - pip install --quiet coveralls
    - coveralls

sudo: false
